# Generated by Django 6.0.2 on 2026-03-13 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('cep', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=255, verbose_name='Bairro')),
                ('localidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('ibge', models.CharField(blank=True, max_length=10, verbose_name='Código IBGE')),
                ('ddd', models.CharField(blank=True, max_length=3, verbose_name='DDD')),
                ('localidade_slug', models.SlugField(max_length=255, verbose_name='Slug da Cidade')),
                ('fonte', models.CharField(choices=[('viacep', 'ViaCEP'), ('awesomeapi', 'AwesomeAPI')], max_length=20, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Consulta CEP',
                'verbose_name_plural': 'Consultas CEP',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(max_length=75, unique=True)),
                ('capital', models.CharField(db_index=True, max_length=75)),
                ('codigo_3', models.CharField(max_length=3, unique=True, verbose_name='Código 3 Dígitos')),
                ('codigo_2', models.CharField(max_length=2, unique=True, verbose_name='Código 2 Dígitos')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='endereço de e-mail')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='primeiro nome')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='sobrenome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='membro da equipe')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='e-mail verificado')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de registro')),
                ('groups', models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='auth.permission', verbose_name='permissões do usuário')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Logins',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OptimizedImageWithTinyPNG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('excluido', models.BooleanField(db_index=True, default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_excluido_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Optimized Image With Tiny PNG',
                'verbose_name_plural': 'Optimized Images With Tiny PNG',
                'ordering': ['-id'],
            },
        ),
    ]
