# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 12:31


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=75, unique=True)),
                ('capital', models.CharField(db_index=True, max_length=75)),
                ('codigo_3', models.CharField(max_length=3, unique=True, verbose_name='C\xf3digo 3 D\xedgitos')),
                ('codigo_2', models.CharField(max_length=2, unique=True, verbose_name='C\xf3digo 2 D\xedgitos')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Pa\xeds',
                'verbose_name_plural': 'Pa\xedses',
            },
        ),
    ]
