# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 16:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodepontoio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
