# Generated by Django 6.0.3 on 2026-04-15 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodepontoio', '0002_userauth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=8, verbose_name='código')),
                ('purpose', models.CharField(choices=[('email_confirm', 'Confirmação de e-mail'), ('password_reset', 'Redefinição de senha')], max_length=20, verbose_name='finalidade')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('is_used', models.BooleanField(default=False, verbose_name='utilizado')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='tentativas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'código OTP',
                'verbose_name_plural': 'códigos OTP',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='bodepontoio_user_id_4524d2_idx')],
            },
        ),
    ]
