# Generated by Django 6.0.2 on 2026-03-06 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bodepontoio', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cep', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='logradouro')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=255, verbose_name='bairro')),
                ('localidade', models.CharField(max_length=255, verbose_name='cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('ibge', models.CharField(blank=True, max_length=10, verbose_name='código IBGE')),
                ('ddd', models.CharField(blank=True, max_length=3, verbose_name='DDD')),
                ('localidade_slug', models.SlugField(max_length=255, verbose_name='slug da cidade')),
                ('fonte', models.CharField(choices=[('viacep', 'ViaCEP'), ('awesomeapi', 'AwesomeAPI')], max_length=20, verbose_name='fonte')),
            ],
            options={
                'verbose_name': 'consulta CEP',
                'verbose_name_plural': 'consultas CEP',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=75, unique=True, verbose_name='nome')),
                ('capital', models.CharField(db_index=True, max_length=75, verbose_name='capital')),
                ('codigo_3', models.CharField(max_length=3, unique=True, verbose_name='código 3 dígitos')),
                ('codigo_2', models.CharField(max_length=2, unique=True, verbose_name='código 2 dígitos')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ('nome',),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='endereço de e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='primeiro nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='e-mail verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='membro da equipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='auth.permission', verbose_name='permissões do usuário'),
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='endereço IP')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'login',
                'verbose_name_plural': 'logins',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OptimizedImageWithTinyPNG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em')),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='caminho')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluído por')),
            ],
            options={
                'verbose_name': 'imagem otimizada com TinyPNG',
                'verbose_name_plural': 'imagens otimizadas com TinyPNG',
                'ordering': ('-id',),
            },
        ),
    ]
