# Generated by Django 6.0.4 on 2026-04-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodepontoio', '0003_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('email_confirm', 'Confirmação de e-mail'), ('password_reset', 'Redefinição de senha'), ('login', 'Login sem senha')], max_length=20, verbose_name='finalidade'),
        ),
    ]
