# Generated by Django 4.2.6 on 2023-10-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodepontoio', '0003_loginrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
