# Generated by Django 5.0.1 on 2024-01-22 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bodepontoio", "0004_alter_loginrecord_id_alter_pais_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OptimizedImageWithTinyPNG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("excluido", models.BooleanField(db_index=True, default=False)),
                ("excluido_em", models.DateTimeField(blank=True, null=True)),
                ("path", models.CharField(db_index=True, max_length=255)),
                (
                    "excluido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_excluido_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Optimized Image With Tiny PNG",
                "verbose_name_plural": "Optimized Images With Tiny PNG",
                "ordering": ["-id"],
            },
        ),
    ]
