# Generated by Django 5.0.4 on 2024-05-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodepontoio", "0006_optimizedimagewithtinypng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginrecord",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="optimizedimagewithtinypng",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pais",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
