# Generated by Django 5.2.8 on 2026-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodepontoio', '0007_alter_loginrecord_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('cep', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=255, verbose_name='Bairro')),
                ('localidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('ibge', models.CharField(blank=True, max_length=10, verbose_name='Código IBGE')),
                ('ddd', models.CharField(blank=True, max_length=3, verbose_name='DDD')),
                ('localidade_slug', models.SlugField(max_length=255, verbose_name='Slug da Cidade')),
                ('fonte', models.CharField(choices=[('viacep', 'ViaCEP'), ('awesomeapi', 'AwesomeAPI')], max_length=20, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Consulta CEP',
                'verbose_name_plural': 'Consultas CEP',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optimizedimagewithtinypng',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
